"""Phase 0 smoke test.

Loads Marlin-2B, runs `caption()` and `find()` on a test clip, prints results.
Intended to prove the environment is wired up correctly before building anything else.

Usage:
    uv run python scripts/smoke_test.py [path/to/video.mp4]

If no path is given, defaults to scripts/_test_clip.mp4 (generated by gen_test_clip.py).
"""

from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path

# torchcodec needs ffmpeg shared libs at dlopen time. glibc reads LD_LIBRARY_PATH
# once at process start and caches it — modifying os.environ later doesn't help.
# So if our preferred lib dir isn't already on the path, re-exec Python with it.
_FFMPEG_LIB = os.environ.get("VIDPROC_FFMPEG_LIB", "/home/elstruck/miniconda3/lib")
if Path(_FFMPEG_LIB).exists() and not os.environ.get("_VIDPROC_LD_FIXED"):
    current = os.environ.get("LD_LIBRARY_PATH", "")
    if _FFMPEG_LIB not in current.split(":"):
        new_env = dict(os.environ)
        new_env["LD_LIBRARY_PATH"] = f"{_FFMPEG_LIB}:{current}" if current else _FFMPEG_LIB
        new_env["_VIDPROC_LD_FIXED"] = "1"
        os.execve(sys.executable, [sys.executable] + sys.argv, new_env)

# Marlin reads these at import time of qwen-vl-utils; set before importing transformers.
os.environ.setdefault("FORCE_QWENVL_VIDEO_READER", "torchcodec")
os.environ.setdefault("FPS", "2.0")
os.environ.setdefault("FPS_MAX_FRAMES", "240")
os.environ.setdefault("FPS_MIN_FRAMES", "4")
os.environ.setdefault("VIDEO_MAX_PIXELS", "200704")

import torch  # noqa: E402
from transformers import AutoModelForCausalLM  # noqa: E402

MODEL_ID = "NemoStation/Marlin-2B"
DEFAULT_CLIP = Path(__file__).parent / "_test_clip.mp4"


def fmt(seconds: float) -> str:
    return f"{seconds:6.2f}s"


def main() -> int:
    video = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CLIP
    if not video.exists():
        print(f"ERROR: video not found: {video}", file=sys.stderr)
        print("Run scripts/gen_test_clip.py first, or pass a path.", file=sys.stderr)
        return 1

    print(f"== Phase 0 smoke test ==")
    print(f"video:  {video}")
    print(f"torch:  {torch.__version__} (cuda={torch.version.cuda})")
    print(f"device: {torch.cuda.get_device_name(0)}")
    print()

    t0 = time.time()
    print(f"loading {MODEL_ID} ...")
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        trust_remote_code=True,
        dtype=torch.bfloat16,
        device_map={"": "cuda"},
    )
    print(f"  loaded in {time.time() - t0:.1f}s")
    print()

    print("running caption() ...")
    t0 = time.time()
    cap = model.caption(str(video))
    cap_elapsed = time.time() - t0
    print(f"  done in {cap_elapsed:.1f}s")
    print()
    print(f"scene: {cap.get('scene', '<missing>')}")
    print("events:")
    events = cap.get("events", []) or []
    for ev in events:
        start = ev.get("start", 0.0)
        end = ev.get("end", 0.0)
        desc = ev.get("description", "")
        print(f"  [{fmt(start)} -> {fmt(end)}] {desc}")
    print()

    query = "something happens"
    print(f"running find(event={query!r}) ...")
    t0 = time.time()
    fr = model.find(str(video), event=query)
    find_elapsed = time.time() - t0
    print(f"  done in {find_elapsed:.1f}s")
    print(f"  raw:       {fr.get('raw', '')!r}")
    print(f"  span:      {fr.get('span')}")
    print(f"  format_ok: {fr.get('format_ok')}")
    print()

    out_path = video.with_suffix(".events.json")
    out_path.write_text(json.dumps(cap, indent=2, default=str))
    print(f"wrote {out_path}")
    print()
    print(f"== OK: caption {cap_elapsed:.1f}s, find {find_elapsed:.1f}s ==")
    return 0


if __name__ == "__main__":
    sys.exit(main())
